In [1]:
import numpy as np 
import pandas as pd 

c:\Users\Fakhri Robi Aulia\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\Users\Fakhri Robi Aulia\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
c:\Users\Fakhri Robi Aulia\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
c:\Users\Fakhri Robi Aulia\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
c:\Users\Fakhri Robi Aulia\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
## Create User (i) Item Matrix that contains Ratings at calculate its average rating using Standard Method
n_users = 5
n_items = 10

user_rating_matrix = np.random.randint(5,size=(n_users,n_items))

In [7]:
np.where(user_rating_matrix>0)

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3,
        3, 4, 4, 4, 4, 4, 4, 4, 4, 4], dtype=int64),
 array([1, 4, 7, 8, 9, 0, 1, 2, 8, 9, 1, 2, 4, 6, 7, 9, 0, 3, 4, 5, 6, 8,
        9, 0, 1, 2, 3, 5, 6, 7, 8, 9], dtype=int64))

In [12]:
average_ratings = np.mean(user_rating_matrix,axis=1)
overall_ratings = np.mean(user_rating_matrix)
overall_ratings

unbiased_ratings = average_ratings-overall_ratings
unbiased_ratings

array([-0.66, -0.06,  0.04,  0.24,  0.44])

In [3]:
## Create User (i) Item Matrix that contains Ratings at calculate its average rating using Shrinkage Term Method